version: '3'
networks:
  main:
services:
  mongo:
    image: mongo:3.6.23
    container_name: microcks-db
    volumes:
      - "~/tmp/microcks-data:/data/db"
    ports:
      - "27019:27017"
  postman:
    image: quay.io/microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime-prod
    ports:
      - "3002:3000"
  app:
    depends_on:
      - mongo
      - postman
    image: quay.io/microcks/microcks:nightly
    container_name: microcks
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTIONS: "-Dloader.path=/deployments/libs"
      JAVA_MAIN_CLASS: "org.springframework.boot.loader.PropertiesLauncher"
      JAVA_APP_JAR: "app.jar"
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017"
      SPRING_DATA_MONGODB_DATABASE: "microcks"
      POSTMAN_RUNNER_URL: "http://postman:3000"
      TEST_CALLBACK_URL: "http://microcks:8080"
      SERVICES_UPDATE_INTERVAL: "0 0 0/2 * * *"
      KEYCLOAK_ENABLED: false
    volumes:
      - ./lib:/deployments/lib
