FROM registry.access.redhat.com/ubi8/nodejs-16-minimal:1-114

MAINTAINER Laurent Broudoux <laurent@microcks.io>

# Some version information
LABEL io.k8s.description="API Contract Testing demonstration for Microcks" \
      io.k8s.display-name="API Contract Testing demo" \
      maintainer="Laurent Broudoux <laurent@microcks.io>"

# Set the running environment as production
ENV PORT 3001

# Define working directory
ENV APP_ROOT=/app
WORKDIR ${APP_ROOT}

# root for build stages
USER root

# Copy files and install dependencies
COPY /* ${APP_ROOT}
COPY bin/ ${APP_ROOT}/bin
RUN cd ${APP_ROOT} \
    && npm install \
    && rm -rdf ${APP_ROOT}/.npm /tmp/v8-compile-cache-0

### Setup user for build execution and application runtime
ENV HOME=${APP_ROOT}
RUN chmod -R u+x ${APP_ROOT}/bin && \
    chgrp -R 0 ${APP_ROOT} && \
    chmod -R g=u ${APP_ROOT} /etc/passwd

### Containers should NOT run as root as a good practice
USER 1001

# Executing defaults
ENTRYPOINT [ "/app/bin/uid_entrypoint_01" ]
EXPOSE 4001