services:
  importer:
    depends_on:
      - microcks
    restart: on-failure
    image: quay.io/microcks/microcks-cli:latest
    volumes:
      - "./src/main/resources:/resources"
      - "./src/test/resources/third-parties:/third-parties"
    entrypoint:
      - microcks-cli
      - import
      - '/resources/order-service-openapi.yaml:true,/third-parties/apipastries-openapi.yaml:true,/third-parties/apipastries-postman-collection.json:false'
      - --microcksURL=http://microcks:8080/api
      - --insecure
      - --keycloakClientId=foo
      - --keycloakClientSecret=bar

  microcks:
    image: quay.io/microcks/microcks-uber:nightly
    ports:
      - "9090:8080"