services:
  importer:
    depends_on:
      - microcks
    restart: on-failure
    image: quay.io/microcks/microcks-cli:latest
    volumes:
      - "./test/resources:/resources"
    entrypoint:
      - microcks-cli
      - import
      - '/resources/order-service-openapi.yml:true,/resources/apipastries-openapi.yml:true,/resources/apipastries-postman-collection.json:false'
      - --microcksURL=http://microcks:8080/api
      - --insecure
      - --keycloakClientId=foo
      - --keycloakClientSecret=bar

  microcks:
    image: quay.io/microcks/microcks-uber:nightly
    ports:
      - "9090:8080"