apiVersion: v1
kind: ServiceAccount
metadata:
  name: microcks-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microcks-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: microcks-operator
  template:
    metadata:
      labels:
        name: microcks-operator
    spec:
      serviceAccountName: microcks-operator
      containers:
        - name: microcks-operator
          image: quay.io/microcks/microcks-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: microcks-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microcks-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkatopics
    verbs:
      - '*'
  - apiGroups:
      - microcks.io
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: microcks-operator
subjects:
  - kind: ServiceAccount
    name: microcks-operator
roleRef:
  kind: Role
  name: microcks-operator
  apiGroup: rbac.authorization.k8s.io