name: build-package
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
jobs:
  build-package:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      # Checkout repository content
      - name: Checkout
        uses: actions/checkout@v3

      - name: Filter contract-testing
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            contract-testing:
              - 'contract-testing-demo/**'

      - name: Set up QEMU
        if: github.repository_owner == 'microcks' && steps.changes.outputs.contract-testing == 'true'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: github.repository_owner == 'microcks' && steps.changes.outputs.contract-testing == 'true'
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Quay.io Registry and setup multi-arch builder
        if: github.repository_owner == 'microcks' && steps.changes.outputs.contract-testing == 'true'
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
          BUILDER=buildx-multi-arch
          docker buildx inspect $BUILDER || docker buildx create --name=$BUILDER --driver=docker-container --driver-opt=network=host

      - name: Build and push container image
        if: github.repository_owner == 'microcks' && steps.changes.outputs.contract-testing == 'true'
        run: |
          cd contract-testing-demo
          docker buildx build --push \
            --platform=linux/amd64,linux/arm64 \
            --builder=buildx-multi-arch \
            --provenance=false \
            --build-arg TAG=01 \
            --file Dockerfile-01 \
            --tag=quay.io/microcks/contract-testing-demo:01 .
          docker buildx build --push \
            --platform=linux/amd64,linux/arm64 \
            --builder=buildx-multi-arch \
            --provenance=false \
            --build-arg TAG=02 \
            --file Dockerfile-02 \
            --tag=quay.io/microcks/contract-testing-demo:02 .
          docker buildx build --push \
            --platform=linux/amd64,linux/arm64 \
            --builder=buildx-multi-arch \
            --provenance=false \
            --build-arg TAG=03 \
            --file Dockerfile-03 \
            --tag=quay.io/microcks/contract-testing-demo:03 .